name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build_fabric:
    if: startsWith(github.event.head_commit.message, '[fabric]')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Make gradlew executable
        run: cd fabric; chmod +x ./gradlew

      - name: Build with Gradle
        run: cd fabric; ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: Plugin Build
          path: build/libs/*.jar
